### PR TITLE
Refactoring Serialisers 

### PR DESCRIPTION
**Pull request by szarnyasg**
WIP

### CODE REVIEW

**Comment by ArnauPrat** [comment]
What does "Drop Sorting Persons as itndid not make any difference"

**Comment by ArnauPrat** [comment]
What does "Drop Sorting Persons as itndid not make any difference" mean?

**Comment by szarnyasg** [comment]
@ArnauPrat We generated the data both ways (on a single node) and the results were the same. Are there any differences when running multiple Hadoop workers?

**Comment by ArnauPrat** [comment]
I am not sure what have you changed, that's why I am asking. Are you talking about the sorting of persons between edge generation steps? Also, be careful not to break determinism. Some determinism related errors only showup when generating datasets larger than SF1.

**Comment by szarnyasg** [comment]
> Are you talking about the sorting of persons between edge generation steps?

This step happens after merging edges. Here's our reverse-engineered workflow figure based on the specification's "Figure 2.2: The Datagen generation process" and the code in [`LDBCDatagen.java`](https://github.com/ldbc/ldbc_snb_datagen/blob/master/src/main/java/ldbc/snb/datagen/).

datagen-workflow

> Some determinism related errors only showup when generating datasets larger than SF1.

We were not aware of that and only tested for SF1. Thanks!

**Comment by ArnauPrat** [comment]
Do you remember the key these persons were sorted by? Maybe this was done
to have some correlation between persons during  activity generation

**Comment by szarnyasg** [comment]
They were sorted with `HadoopPersonSortAndSerializer` which uses the `BlockKeyComparator`:

https://github.com/ldbc/ldbc_snb_datagen/blob/c966fda315009b36ca6e0cf91c47dbfaf1f312c9/src/main/java/ldbc/snb/datagen/hadoop/serializer/HadoopPersonSortAndSerializer.java#L167-L169

https://github.com/ldbc/ldbc_snb_datagen/blob/c966fda315009b36ca6e0cf91c47dbfaf1f312c9/src/main/java/ldbc/snb/datagen/hadoop/key/blockkey/BlockKeyComparator.java#L50-L58

**Comment by ArnauPrat** [comment]
Then, it is likely that this is related to determinism. Probably we want it
there to make sure that all persons belonging to a block are processed
together for some reason. If this is not done, it is likely that for
settings with multiple different number of workers, we get different
results. But i am not 100% sure. It is worth to make a test with SF10 with
different number of workers.

**Comment by ArnauPrat** [comment]
By the way, I used to compare datasets with this script:
https://github.com/ldbc/ldbc_snb_datagen/blob/master/tools/testDatasets.sh

**Comment by szarnyasg** [comment]
@ArnauPrat thanks! I reverted that commit for now. We will finish the refactoring and will later come back to the determinism issue on SF10 data. See issue #104.

**Comment by ArnauPrat** [comment]
> @ArnauPrat thanks! I reverted that commit for now. We will finish the refactoring and will later come back to the determinism issue on SF10 data. See issue #104.

Thanks @szarnyasg 
I agree that it will be better to first refactor and then look for possible optimizations.

**Comment by szarnyasg** [comment]
The internal ids in the Turtle representations changed slightly, see https://gist.github.com/szarnyasg/d5751e67acf9e5916fde895b7b3129c1

**Pull request merged**
