### PR TITLE
Rewrite Raw serializer in Scala

### PR DESCRIPTION
**Pull request by dszakallas**
TODOs left:
- [x] Spark 2.4 not working. Might need a project matrix if we want to avoid reflection. What to do? __Removing support for Spark 2.4__
- [x] Dates are Longs now. Need to map back in BI, Interactive outputs __Store as long and introduce extra layer, as this is the simplest solution__
- [x] Birthdays messed up?
- [x] Parquet not integrated yet

### CODE REVIEW

**Comment by szarnyasg** [comment]
It seems factor generation is broken, could you take a look?

```bash
$ export SF=0.003 && \
  rm -rf sf${SF}-bi/ && \
  ./tools/run.py ./target/ldbc_snb_datagen_${PLATFORM_VERSION}-${DATAGEN_VERSION}.jar -- \
  --format csv --scale-factor ${SF} --mode bi --output-dir sf${SF}-bi --explode-edges --generate-factors
$ ls sf0.003-bi/
graphs
# no factors directory
```

**Comment by dszakallas** [comment]
Nice catch, I overlooked this detail unfortunately.

**Comment by szarnyasg** [comment]
There are some slight changes in the output data set. For SF1, used the following command to generate:

```bash
$ time ./tools/run.py ./target/ldbc_snb_datagen_${PLATFORM_VERSION}-${DATAGEN_VERSION}.jar --parallelism 32 --memory 800G -- --format csv --scale-factor ${SF} --mode bi --output-dir ... --explode-edges --generate-factors
```

#### Old
```bash
$ cat sf1-bi-csv-serializer/graphs/csv/bi/composite-projected-fk/initial_snapshot/dynamic/Post/* | sort | head -n 3
2010-01-03T20:20:36.280+00:00|3||77.245.239.11|Firefox|uz|About Wolfgang Amadeus Mozart, ncial security. DuringAbout Thomas Jefferson, al slave trade, and adAbout Hen|108
2010-01-03T22:36:40.629+00:00|200053|photo200053.jpg|27.112.123.203|Firefox|||0
2010-01-03T22:36:41.629+00:00|200054|photo200054.jpg|27.112.123.203|Firefox|||0
```

#### New
```bash
$ cat sf1-bi-compressed-serializer/graphs/csv/bi/composite-projected-fk/initial_snapshot/dynamic/Post/* | sort | head -n 3
2010-01-03T20:20:36.280+00:00|3|""|77.245.239.11|Firefox|uz|About Wolfgang Amadeus Mozart,  financial security. During About Marlene Dietrich, l films in the post-war y|108
2010-01-07T09:23:00.337+00:00|260661|""|1.45.145.243|Internet Explorer|uz|About Jim Carrey, obe Awards for Best Actor. In 2000, he gained further recognition for h|89
2010-01-09T08:59:10.560+00:00|189597|photo189597.jpg|27.124.91.230|Firefox|""|""|0
```

Two observations:
1. The attribute values are slightly different. Maybe there are slight differences in how the pseudo RNG is accessed by each block?
2. The new serializer adds quotes automatically for empty cells.

**Comment by szarnyasg** [comment]
The sizes of the data sets seem correct: the difference between the old and the new data set for SF100 is <1%.

```
$ du -d0 sf100-bi-*-serializer/graphs/csv/bi/composite-projected-fk/
101668904       sf100-bi-compressed-serializer/graphs/csv/bi/composite-projected-fk/
101285340       sf100-bi-csv-serializer/graphs/csv/bi/composite-projected-fk/
```

**Comment by szarnyasg** [comment]
There are missing TagClasses in the serializer.

E.g. I generated SF0.3. In this, the TagClass node 239 is referred to as the endpoint of an `isSubclassOf` edge but it does not exist in the `TagClass/` directory:
```bash
$ ag '"239"' TagClass*
TagClass_isSubclassOf_TagClass/part-00000-6e64b086-2114-44ed-922f-eb5aa0f65710-c000.csv
2:"211"|"239"
```

**Comment by szarnyasg** [comment]
Tested it locally with the [BI Neo4j loader](https://github.com/ldbc/ldbc_snb_bi/tree/main/cypher) and it loads correctly :+1:

**Review by szarnyasg — APPROVED** [review]

**Pull request merged**
